# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - release
  - devel

r_check_args: '--as-cran --use-valgrind'

env:
  global:
    - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
    - _R_CHECK_SYSTEM_CLOCK_=false

addons:
  apt:
    packages:
      - valgrind

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
